services:
  code-server:
    image: ghcr.io/linuxserver/code-server:4.123.0
    container_name: code-server
    restart: unless-stopped
    environment:
      PASSWORD=${PASSWORD}
      TZ=America/Fortaleza
    volumes:
      - ./code-server:/config
      - ./workspace:/workspace

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - code-server